日曜の音楽再生アプリを移植　実機で動作確認できてない（許して）
enpitut2019/dj-yusaku pull request #1
Opened 2019-10-09 07:18 UTC by amylaseF85

## 概要
* 日曜に自分と中村の側で作った、音楽再生アプリを現在のプロジェクトに移植

## 課題
* UIは仮置きなので日曜に作ったイメージに合致していない
* **実機での動作確認をお願いします**

2019-10-09 07:20 UTC, yaplus commented
関係ないですけど名前を書く時は @yaplus のように書きましょう

2019-10-09 07:21 UTC, amylaseF85 commented
了解しました

2019-10-09 07:24 UTC, yaplus commented
Forkした環境であっても `master` ブランチで作業するのはあまり良くないので、せめて作業用に `develop` ブランチを切るくらいはしましょう。  
本当はさらに `develop` から作業別に `feature` ブランチを切るのが良いですが、面倒かもしれないので。（ https://github.com/enpitut2019/dj-yusaku/wiki/コードの書き方とTips も参照 ）

2019-10-09 08:13 UTC, yaplus requested changes
レビューしました。バグがあるのでレビューに従って直してきてください。（なお、これらの点を簡単に直した状態で実機での動作確認はできています。）  
**Info.plistの修正を忘れずに。**  
@amylaseF85 の実機で動かない件については後日相談しましょう。

2019-10-09 08:13 UTC, yaplus commented on DJYusaku/FirstViewController.swift
> +class ViewController: UIViewController, MPMediaPickerControllerDelegate {
FirstViewControllerの間違いでは？（エラーが出ている）

2019-10-09 08:13 UTC, yaplus commented on DJYusaku/FirstViewController.swift
> +        player = MPMusicPlayerController.applicationMusicPlayer
メディアライブラリへのアクセスを行うための許可をFirstViewの読み込み時に確認しなければならないはず（同時に、Info.plistにNSAppleMusicUsageDescriptionを加える必要がある）

2019-10-09 08:29 UTC, yaplus commented
Issueの名前はちゃんと書きなさーい😾💨

2019-10-10 08:10 UTC, amylaseF85 commented on DJYusaku/FirstViewController.swift
> +class ViewController: UIViewController, MPMediaPickerControllerDelegate {
ご指摘のとおりです

2019-10-10 08:10 UTC, amylaseF85 commented on DJYusaku/FirstViewController.swift
> +        player = MPMusicPlayerController.applicationMusicPlayer
確認するための処理の追加を行います

2019-10-10 14:41 UTC, closed without merging