SearchViewControllerで選択したものをRequestsに追加できる機能を実装
enpitut2019/dj-yusaku pull request #12
Opened 2019-10-25 17:47 UTC by bldsky

## 概要
<img src="https://user-images.githubusercontent.com/25448272/67591380-410d6f80-f798-11e9-9e0f-3143366ec37a.gif" width="140">
検索画面で+マークを押した曲をリクエスト画面に追加できる機能を実装した

## 気になってる点
* Notification.Nameを今のところRequestQueue.swiftに書いているができれば設定用のファイルに書きたい(これは僕が知識不足なだけであるのかもしれない)
* NotificationCenterでtableView.reloadDataを呼ぶ関数を呼んでいるだけなのでもっといい書き方がありそう

## 問題点
* 検索画面で+ボタンを押したときのフィードバックがないので押されたかどうかわからない

## してほしいこと
* 曲の追加ができてるかどうか確認お願いします

## これからやろうとしていること
* +ボタンを押したときのフィードバックを付けます

2019-10-26 00:50 UTC, yaplus commented
> NotificationCenterの関数の引数に送り先のオブジェクトと受け取り先のオブジェクトを指定する引数をnilにしているがこれでいいらしい(調べてはいるがぼんやりしてます。情報ください)

おそらくだけどnilだと通知がブロードキャストになってオブジェクト名書くとそのオブジェクトにだけ通知されるんじゃないかな  
今回の場合だと通知送る側(Queue)はnilでいいけど受け取る側は通知元を指定してもいいと思う(ただ、通知名がユニークなら指定する必要もないかな)

2019-10-26 03:03 UTC, bldsky commented
受け取る側に(object: RequestQueue.shared)を入れると何故か通知受け取らなくなってしまうんですよね

2019-10-26 04:19 UTC, yaplus commented
@bldsky
確かにざっと調べたらみんなobject:nilにしてるんだけど、ドキュメントの使い方的にはobjectに発行元指定するのは間違えてないから、Queue.sharedが何か悪いのかな…

2019-10-26 04:20 UTC, yaplus commented
まあ、nilでうまくいってるからとりあえずそれでいいかな？(どうせ通知名が被る事もないし)

2019-10-26 10:15 UTC, bldsky commented
## 追記

- [x] +ボタンを押したときのフィードバックを付けた
- [x] リクエストした曲がRequestQueueに追加されるまでその曲は押せないようにした(=連打できないように)

## 気になっていること
* Notification.Nameが長いし名前が簡潔でない気がするので名付けに自信ニキ頼みます。

2019-10-27 07:29 UTC, bldsky commented
適当にレビューしてもらったらmergeしたいです

2019-10-27 09:09 UTC, yaplus requested changes
レビューしたので指摘したところに納得できれば直しておいてください。

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/RequestQueue.swift
> +//Notification.Nameをどこに書けばいいかまだ決まっていない
ここでいいのでこのコメントは消しておいてください

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/RequestQueue.swift
>      // TODO: requestsの中身を追加する関数と消去する関数
実装できているならコメントを消した方がいいと思います。

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +        tableView.reloadData()
これがメインスレッドで行われてないのは、キューに追加される時点ではRequestViewがバックグラウンドに回ってるからでしょうか？動作的に大丈夫そうならこれでOKですが、何か画面が壊れそうな場合はメインスレッドに移した方がいいのではないのでしょうか。

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/RequestQueue.swift
> +    func deleteRequest(indexPath: Int){
引数はInt型なのにindexPathという名前はおかしいでしょう。適切な名前（たとえば"index"など）にしておいてください。
名前もremoveRequestの方がrequests.removeと整合性がとれるかも？

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/RequestQueue.swift
> +    func getRequest(indexPath: Int) -> MusicDataModel {
上と同様です。

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/RequestQueue.swift
> +    func addRequest(musicDataModel: MusicDataModel){
addRequestなら引数名はmusicDataModelじゃなくてrequestでいいのでは？
引数名は何を扱っているのかを分かりやすくするためのものとして使ってください。

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/SearchMusicTableViewCell.swift
> +        button.isEnabled = false
これ機能してなくない？連続でリクエストできたんだけど

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/SearchViewController.swift
> +        let alert = UIAlertController(title: title, message: "をリクエストしました", preferredStyle: UIAlertController.Style.alert)
英語にしてもらえると嬉しい（あとで他の部分も英語に直したコミットを上げるので）

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/RequestQueue.swift
> +    static let searchCellToSearchVCName = Notification.Name("searchCellToSearchVcName")
これいらなくないですか？SearchViewControllerがrequestQueueToRequestsVCName購読（リクエストを追加できた保証がある時点で通知）するべきって以前指摘した気がするんですけれども。

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/SearchViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(registerRequestAlert), name: .searchCellToSearchVCName, object: nil)
RequestQueue.swift のレビューにも書きましたが.requestQueueToRequestsVCNameにした方がいいですね

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/SearchViewController.swift
> +        button.isEnabled = true
SearchMusicTableViewCell.swift の38行目が機能してないのこいつのせいじゃん  
button.isEnabled = trueはSearchViewController.swiftのUITableViewDataSourceのtableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath)の中でやった方がいいと思います。

```swift
extension SearchViewController: UITableViewDataSource {
// ...
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "SearchMusicTableViewCell", for: indexPath) as! SearchMusicTableViewCell
        
        let item = results[indexPath.row]
        cell.title.text       = item.title
        cell.artist.text      = item.artist
        cell.artworkUrl       = item.artworkUrl
        cell.artwork.image    = defaultArtwork
        cell.button.isEnabled = true      // ここを追記
        // ついでにこの部分の"="の部分を上みたいに揃えておいてくれると綺麗

// ...
```

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/SearchViewController.swift
> +        cell.artworkUrl = item.artworkUrl
"="の部分揃えてたんだから揃えてくれや😭

2019-10-27 09:09 UTC, yaplus commented on DJYusaku/SearchViewController.swift
> +        button.isEnabled = true
ちなみにこれに直すとちゃんと機能することを確認した

2019-10-27 09:46 UTC, bldsky commented on DJYusaku/SearchViewController.swift
> +        button.isEnabled = true
これは僕もやったけど一度押したものはその画面ではもう押せなくなるってことでいいの？

2019-10-28 03:05 UTC, bldsky commented
指摘された点の修正とrequestsの監視(didSet)追加を行いました。これで追加されてないのにalertだけ出るみたいな挙動がなくなるはずです(ほんとか？)

2019-10-28 03:46 UTC, yaplus commented
@bldsky 
お疲れさまです

> ## 概要
> * 指摘された点の修正とrequestsの監視(didSet)追加を行いました。これで追加されてないのにalertだけ出るみたいな挙動がなくなるはずです(ほんとか？)

プロパティ監視(あるいはObj-CのKVO)はもっとリアルタイム性の高いものに使うような気がします。（たとえば、ExcelのマクロやT*huの健康計算機みたいに、入力された値を監視して新しい結果を計算するような場合）  
今回のように　子機が親機へ追加リクエスト→親機がキャッチして追加できるか判断→追加できればその旨を通知　っていうのは単純に処理ができたら通知（元々の実装）でいいと思うのですが…。

> Bluetooth実装後だとalertが全員に出そうな気がしますが、今からそれを想定してやりたくないです。

これどうなるんだろう。とりあえず保留でいいんじゃないでしょうか。

2019-10-28 03:48 UTC, yaplus commented
でもちゃんと動いてるならとりあえずこれでいいか！

2019-10-28 03:53 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +        present(alert, animated: true)
ここで requestedAlert を別の関数にしたことについて意図があったりしますか？

2019-10-28 03:56 UTC, yaplus approved these changes

2019-10-28 03:56 UTC, yaplus commented
コメントしたところ（requestedAlertの意図）が大丈夫ならマージしちゃって大丈夫だと思います

2019-10-28 04:02 UTC, yaplus reviewed
全部みました

2019-10-28 04:03 UTC, bldsky commented
間違えてresolveしちゃった......
updateRequestsはリクエストをアップデートする関数として記述しているためアラートを出す処理は分けて書いといたほうがわかりやすいかな.....って思って書きました

2019-10-28 04:05 UTC, yaplus commented
> updateRequestsはリクエストをアップデートする関数として記述しているためアラートを出す処理は分けて書いといたほうがわかりやすいかな.....って思って書きました

うーん、難しいね。それくらいならアラートを出す処理を他で使い回すわけじゃないなら纏めちゃっていいかも。

2019-10-28 04:07 UTC, bldsky commented
纏めてコメント入れときます

2019-10-28 04:08 UTC, yaplus commented
updateRequestsって名前だと画面更新する感じだけど、実際にはイベントハンドラなわけだから引数にNotidicationの詳細持ってくるわけだし、その辺の塩梅が難しいかも。  
イベントハンドラの中で「画面を更新する処理」「アラートを出す処理」をしていると言った方がいいのかもしれない。

2019-10-28 04:09 UTC, bldsky commented
名前変えようかな

2019-10-28 04:12 UTC, yaplus commented
handleRequestUpdated() とかどうだろう

2019-10-28 04:14 UTC, bldsky commented
まあいいんじゃない、ってなったので変更します

2019-10-28 04:27 UTC, bldsky commented
mergeします

2019-10-28 04:42 UTC, merged