検索画面で選択された楽曲を、再生用のキューに追加・再生する機能の実装
enpitut2019/dj-yusaku pull request #16
Opened 2019-10-29 05:34 UTC by amylaseF85

## 概要
- 検索ボタンで曲を選択する（+ボタンを押す）と再生キューに楽曲が追加される
- 再生キューに楽曲が最初に追加される時、自動で再生
    - 再生・停止の各ボタンが追加されるまでの暫定処理
    

## 追加・変更点
- 楽曲IDの取得の追加
    - 検索結果に楽曲IDを保存するように変更
    - MusicDataModelに楽曲IDが登録できるように変更
    - #12で追加されたnotificationに、一緒に楽曲IDも送信するように変更

- func makePlayerStoreQueueDescriptor(songID: String) -> MPMusicPlayerStoreQueueDescriptor
    - 楽曲のIDからAppleMusic内の楽曲のdescripterを作成

- func applyMusicPlayerControllerQueue(songID : String)
    - 楽曲のIDからdescripterを作り、playerのqueueに追加
    - 起動後初めて楽曲が追加される時のみ呼び出される

- func insertMusicPlayerControllerQueue(songID : String)
    - 楽曲のIDからdescripterを作り、playerのqueueの最後尾に追加
    - 2回目以降の追加で呼び出される

## @amylaseF85 が実機で確認したこと
- はじめて検索画面から楽曲を選択した時、自動で再生されることを確認
    - applyMusicPlayerControllerQueueの確認
- すでに楽曲Aが再生中（＝再生キューに楽曲がある）に楽曲Bを追加した時、Aが終了後にBが再生されることを確認
- すでに楽曲Aが再生中に楽曲B,Cを2つ追加した時、Aの次にBが再生されることを確認
    - insertMusicPlayerControllerQueueの確認

## 問題
- セルを表示するためのMusicDataModelを入れたキューと、playerのキューがそれぞれ存在する

## 今後
- Request画面の下のセルに再生中の楽曲の情報を出す

2019-10-31 02:43 UTC, yaplus requested changes
ざっとレビューさせていただきました。いい感じだと思います。レビュー箇所を確認してみてください。

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +    private var mediaItems: [MPMediaItem] = []
mediaItems[]は今のところ使われていないようですが、必要ですか？

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +        }
再生ボタン作るのでこの部分はなんとかしたいですね。たぶん
```swift
insertMusicPlayerControllerQueue(songID: songID)
```
だけにしたい

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +extension RequestsViewController{
UIViewControllerへの追加部分はextensionにする必要はないです。  
今のところは、extensionにするのはViewController以外のprotocolの実装だけにしていただきたい。

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +    }
多分この処理は再生ボタンを押した時の処理になるのかな？  
キューへの追加してるっぽい部分は、処理の整合性的をとるとinsertMusicPlayerControllerQueue()を使うようにしたほうがいいのではないか？と思いました。たとえば
```swift
    func applyMusicPlayerControllerQueue(songID : String){
         insertMusicPlayerControllerQueue(songID: songID)
         musicPlayerApplicationController.play()
     }
```
のような感じ。  
でも、この関数は初回でしか使わないからこうしてるようなので、再生ボタンを追加した時には  
```swift
    @IBAction func playMusicPlayerController(){
         musicPlayerApplicationController.play()
     }
```
だけになりそう。
対になる処理（停止ボタンを押したときの処理）もそのうち必要になりそう。

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +            print("mutableQueue.items.count:", mutableQueue.items.count)
デバッグ出力は動作を確認できたら削除しておいてください。

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/SearchMusicTableViewCell.swift
> +    var songID : String!
そういえばテーブルのセルにartworkUrlとsongID持たせる必要あるんだっけ？  
必要なければ消しちゃいたいんだけど（同じ情報は対応するインデックスのMusicDataModelが持ってるはずなので）、データの受け渡しに必要であれば色々と考えなきゃいけないですね。

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/SearchViewController.swift
> +        cell.songID           = item.songID
上と同様です。

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/MusicDataModel.swift
> +    var songID : String    // 曲のID
コメントアウトのインデントを揃えてください。

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
>          guard let title = notification.userInfo!["title"] as? String else { return }
ここは一つのguard式にまとめちゃって良さそう。
```swift
        guard let songID = notification.userInfo!["songID"] as? String
           && let title  = notification.userInfo!["title"]  as? String else { return }
```

2019-10-31 02:43 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +    }
実質的にMPMusicPlayerStoreQueueDescriptor()と同じなので関数化する必要ない気がするのですが、どうでしょうか。

2019-10-31 03:10 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> +extension RequestsViewController{
了解です

2019-10-31 03:10 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> +            print("mutableQueue.items.count:", mutableQueue.items.count)
了解です

2019-10-31 03:12 UTC, amylaseF85 commented on DJYusaku/MusicDataModel.swift
> +    var songID : String    // 曲のID
了解です

2019-10-31 03:17 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> +    }
よく考えたらそうですね
調べてたらキューに追加する曲を、ローカルの中から選択する場合とAppleMusicから選択する場合で処理が違ったようなので、後々を考えるとこっちの方がいいかなと思ったのですが、結局返す型が異なってくるので意味ないです

2019-10-31 03:30 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> +        }
了解です

2019-10-31 03:38 UTC, yaplus commented
@amylaseF85 
もしかして曲が無事に再生されたらRequestQueueから削除する処理を入れてない？

2019-10-31 03:40 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
>          guard let title = notification.userInfo!["title"] as? String else { return }
`        guard let songID = notification.userInfo!["songID"] as? String,
              let title  = notification.userInfo!["title"]  as? String else { return }`
こうではないですか？

2019-10-31 03:43 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
>          guard let title = notification.userInfo!["title"] as? String else { return }
```
        guard let songID = notification.userInfo!["songID"] as? String,
              let title  = notification.userInfo!["title"]  as? String else { return }
```
こうではない？

2019-10-31 03:44 UTC, amylaseF85 commented
とりあえずレビューを見据えて、とにかく音楽が流れるように実装しているので、削除関係は実装してないです

2019-10-31 03:44 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
>          guard let title = notification.userInfo!["title"] as? String else { return }
そうですね（すいません）

2019-10-31 03:50 UTC, yaplus commented
> とりあえずレビューを見据えて、とにかく音楽が流れるように実装しているので、削除関係は実装してないです

レビューで曲のスキップはできるようになってて欲しいなあ。  
雑な実装で良ければ、RequestQueueが`MPMusicPlayerControllerNowPlayingItemDidChangeNotification`を購読するとすぐできそうだけど。

2019-10-31 03:51 UTC, amylaseF85 commented
多分実装中調べてパッと出てこなかったから後回しにしてた思います
その辺何使えばいいか、分かればお願いします
（再生が終わったというイベントや通知が出るとか）

2019-10-31 03:52 UTC, amylaseF85 commented
曲のスキップは別ブランチで実装済です
別作業な気がしたのでこのプルリクに出ないようにしてます

2019-10-31 03:52 UTC, amylaseF85 commented
> > とりあえずレビューを見据えて、とにかく音楽が流れるように実装しているので、削除関係は実装してないです
> 
> レビューで曲のスキップはできるようになってて欲しいなあ。
> 雑な実装で良ければ、RequestQueueが`MPMusicPlayerControllerNowPlayingItemDidChangeNotification`を購読するとすぐできそうだけど。

なるほど？

2019-10-31 04:02 UTC, yaplus commented
> 曲のスキップは別ブランチで実装済です
> 別作業な気がしたのでこのプルリクに出ないようにしてます

別プルリクでいいけど、そのブランチをこのブランチ（amylaseF85:feature/play-music）にマージしてこのプルリクにくっつけてもいいかも。  

> > レビューで曲のスキップはできるようになってて欲しいなあ。
> > 雑な実装で良ければ、RequestQueueが`MPMusicPlayerControllerNowPlayingItemDidChangeNotification`を購読するとすぐできそうだけど。
> 
> なるほど？

これで動くかどうかはわからないけど、イメージとしては次のような感じです。
```swift
class RequestQueue{

    private init(){
        // 曲が切り替わった時に呼ばれる通知を購読
        NotificationCenter.default.addObserver(self, selector: #selector(handlePlayingItemChanged), name: NSNotification.Name.MPMusicPlayerControllerNowPlayingItemDidChange, object: nil)
    }

    // ...

    // 曲が切り替わった時に呼ばれる処理
    private handlePlayingItemChanged(){
        // とりあえず先頭の曲が削除されたことにしておく
        requests.remove(at: 0)
    }

```

2019-10-31 04:06 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
>          guard let title = notification.userInfo!["title"] as? String else { return }
モーマンタイ

2019-10-31 04:10 UTC, amylaseF85 commented
> `NotificationCenter.default.addObserver`の`object`はnilじゃなくてプレイヤーにした方がいいかもしれないんだけど、今の実装だとRequestViewControllerがstaticじゃないplayerを持っているのでそれはできなさそう。

とりあえずobject: nilにしときます

2019-10-31 04:12 UTC, amylaseF85 commented
> 別プルリクでいいけど、そのブランチをこのブランチ（amylaseF85:feature/play-music）にマージしてこのプルリクにくっつけてもいいかも。
さっきのレビュー全部終わったらマージしてくっつけます

2019-10-31 04:13 UTC, yaplus commented
将来的にはPlayerはRequestQueueと同じようにシングルトンな何かに持たせた方がいいのかも。  
いっそのことRequestQueueにまとめた（1つのオブジェクトがリクエスト用キューと音楽プレイヤーを管理する）方が都合が良いかもしれないしれない。

2019-10-31 04:13 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
>          guard let title = notification.userInfo!["title"] as? String else { return }
もーまんたい

2019-10-31 04:22 UTC, amylaseF85 commented
@yaplus @bldsky 


> 将来的にはPlayerはRequestQueueと同じようにシングルトンな何かに持たせた方がいいのかも。
> いっそのことRequestQueueにまとめた（1つのオブジェクトがリクエスト用キューと音楽プレイヤーを管理する）方が都合が良いかもしれないしれない。

これに関連するか分からないけど、
今playerが持つキューとRequestQueue（のMusicDataModel）が2つあると思うんですけど、どちらかというとRequestQueueにまとめるというより、playerが持つキューからセルの表示に必要な情報を参照するようにしたい
（これまた別件で、セルの削除操作を実装していた時に、2つ削除操作が出てきてイヤだと感じたため）

2019-10-31 04:36 UTC, yaplus commented
@amylaseF85 

> 今playerが持つキューとRequestQueue（のMusicDataModel）が2つあると思うんですけど、どちらかというとRequestQueueにまとめるというより、playerが持つキューからセルの表示に必要な情報を参照するようにしたい

それはそう…  
playerが持つキューのdescripterにアートワーク情報とかがあればできそうだけど、その辺は自分もわかんないです。

2019-10-31 04:43 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> +    private var mediaItems: [MPMediaItem] = []
別件で、セルの削除をする時に削除の対象となるアイテムを参照する時に必要になります
本当はinsertした時に追加した結果をmediaItemsに保存するようにしとくのですが、後で任意のセルの楽曲を削除する機能を実装してた時にそれに気づいたので、宙吊りになっている状態です

要するに、今後削除機能をどう実装するかにも依るんですが、再生だけだったらなくてもOKです

2019-10-31 04:48 UTC, amylaseF85 commented
> @amylaseF85
> 
> > 今playerが持つキューとRequestQueue（のMusicDataModel）が2つあると思うんですけど、どちらかというとRequestQueueにまとめるというより、playerが持つキューからセルの表示に必要な情報を参照するようにしたい
> 
> それはそう…
> playerが持つキュー要素（descripter？）にアートワーク情報とかがあればできそうだけど、その辺は自分もわかんないです。

MPMediaItemで情報を持たせると、この先ほかの基本機能の実装をする時に都合がよさそう、というのは今回の作業中調べてて思った
https://developer.apple.com/documentation/mediaplayer/mpmediaitem

2019-10-31 04:50 UTC, amylaseF85 commented
今思ってるのは、検索でAPI叩くとJSONが返ってくるけど、その中で自分たちが必要な情報だけ取り出して、MPMediaItemをコンストラクタかなんか通して作れればいいんだけど、その辺の情報が調べ方が分からないのも含めて出てこなかった

2019-10-31 04:50 UTC, yaplus commented
@amylaseF85 
もともとAppleのフレームワークに適切なデータ型があればそっち使った方がいいかなと思ってMusicDataModel作ってたし、MPMediaItemが都合が良さそうならもうMusicDataModel使わなくていいと思うなあ。

2019-10-31 05:17 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +                mutableQueue.insert(descripter, after: mutableQueue.items.last)
ここでmutableQueue.itemsで[MPMediaItem]をとってこれるっぽいから、RequestQueueをここで同期させるのが良さそう

2019-10-31 05:17 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +                mutableQueue.insert(descripter, after: mutableQueue.items.last)
将来的な話です

2019-10-31 05:19 UTC, yaplus commented
> もともとAppleのフレームワークに適切なデータ型があればそっち使った方がいいかなと思ってMusicDataModel作ってたし、MPMediaItemが都合が良さそうならもうMusicDataModel使わなくていいと思うなあ。

検索画面では素直に引き続きMusicDataModel使った方が良さそう

2019-10-31 05:26 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> +                mutableQueue.insert(descripter, after: mutableQueue.items.last)
https://dev.classmethod.jp/smartphone/iphone/ios-10-mp-music-player-application-controller/
前に紹介された記事だと、
`perform(queueTransaction, completionHandler)`
のcompletionHandlerでmediaItems: [MPMediaItem]に記録しているので、こっちもそうした方が良さそう
queueTransactionの中だと、mutableQueueに挿入失敗した時RequestQueueにだけ追加されると思う

```
            musicPlayerApplicationController.perform(queueTransaction: { mutableQueue in
                let descripter = MPMusicPlayerStoreQueueDescriptor(storeIDs: [songID])
                mutableQueue.insert(descripter, after: mutableQueue.items.last)
            }, completionHandler: { queue, error in
                self.musicItems = queue.items
                if (error != nil){
                    // TODO: キューへの追加ができなかった時の処理を記述
                }
            })
```
こうするつもりだったので`self.musicItems = queue.items`をRequestQueueに入れるようにする

2019-10-31 05:36 UTC, amylaseF85 commented on DJYusaku/SearchMusicTableViewCell.swift
> +    var songID : String!
見直したんすけど、現状@bldskyが作ってくれたNotificationに一緒に乗せて送ってるので、結局必要そうです

2019-10-31 06:04 UTC, yaplus commented
再生キューの話は結構今までの実装を見直すことになりそうだし、直接一緒に考えた方が良さそうだから、とりあえず今回は再生・スキップボタンが動くところまでにしておいて機会をみて話し合いましょう

2019-10-31 06:33 UTC, amylaseF85 commented
レビュー箇所修正して、skipボタンの進捗をmergeしてきた
言い忘れてたんですけど、実際skip押した時、キューに何もないと落ちます

2019-10-31 12:24 UTC, amylaseF85 commented
マージする場合、スキップの動作確認を一応お願いします
スマホ接続するための変換セットを学校に置いてきたので明日まで確認できないです…

2019-10-31 14:15 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +                mutableQueue.insert(descripter, after: mutableQueue.items.last)
確かに、completionHandlerのqueueに入ってくるのは追加後のキューだからそっちの方がいいと思います。

2019-10-31 14:15 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> +        //FIXME: 再生キューに何もないと落ちる
```swift
guard musicPlayerApplicationController.nowPlayingItem != nil else { return }
```
とか入れると良さそう？

2019-11-01 00:50 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> +        //FIXME: 再生キューに何もないと落ちる
一応追加してみたけど、.play()を呼び出さないと結局止まってるかどうか分からない感じなので、ボタンを追加したら再度検討したい

2019-11-01 00:53 UTC, amylaseF85 commented
> マージする場合、スキップの動作確認を一応お願いします
> スマホ接続するための変換セットを学校に置いてきたので自分は明日まで確認できないです…

確認しました、キューに楽曲があれば次の曲入ります

2019-11-01 01:48 UTC, amylaseF85 commented
@yaplusが作ってくれました

2019-11-01 02:08 UTC, yaplus commented
実はバグまみれだけどレビュー用には一応動く感じ  
あと #13 で再生ボタン追加したし、NowPlayingのところに再生中の曲の情報出したいから、とりあえずこのプルリクと #16 をmasterにマージしちゃいます

2019-11-01 02:15 UTC, yaplus approved these changes
みました

2019-11-01 02:15 UTC, merged