MultipeerConnectivityでデバイス間接続を可能にする
enpitut2019/dj-yusaku pull request #24
Opened 2019-11-06 10:36 UTC by tsuu32

## 概要

MultipeerConnectivityのラッパーライブラリConnectionController.swiftを作成。
ConnectionController.swiftで初期化、advertising、browsingが可能。
ConnectionControllerDelegate.swiftのメソッドを実装することで、browsing中に見つかった時の処理、データが送られてきた時の処理をかける。

## やったこと

- [x] 初期表示でのWelcomeViewControllerのDoneボタンをdisable
  - [ ] 初期表示でのWelcomeViewControllerのDoneボタンを隠す
- [x] Join as the DJボタンでセッションを初期化してadvertising開始
  - [x] 再生中の曲のインデックスの自己管理
- [x] Join as a ListenerボタンでDJ選択画面の表示 (Browsing開始)
  - [x] DJ選択画面で接続可能なDJをTableViewで表示
  - [x] DJ選択画面で表示された接続可能なDJを表すTableViewCellをタップして接続
- [x] connectionController(didReceiveData data: Data, from peerID: MCPeerID)に受け取った時の処理をかけるようにする
- [ ] DJになった後に自分がDJであることをわかる表示 (ナビゲーションバーに色付け？)

#### 重要な情報

Notificationは使っていません。

デバイス間で接続するのはとりあえずできました。
送受信に関してですが、送る方は @bldsky が頑張ってます。
受け取る処理がバグってます。
(WelcomeViewControllerでのConnectionController.shared.delegate = selfがバグってるせい？)

## やってほしいこと

「リスナは何を送ればいいか」、「DJは受け取った時何をするか」を知りたい。

それと、DJが持つReuestQueue(音楽再生のキュー)の情報を、リスナにどう送るかなどを考えなくちゃならない。(キューのリスナとの同期、リスナはキューから削除できるのか、スキップできるのかなど)

2019-11-07 11:58 UTC, amylaseF85 reviewed
デバックとかやってないんでアレだけど、ぱっと見で気になったところを指摘しておきます

2019-11-07 11:58 UTC, amylaseF85 commented on DJYusaku/ConnectionController.swift
> +        browser.delegate = self
```swift
  var connectableDJs: [MCPeerID] = []
```
と
```swift
self.connectableDJs = []
```
どっちかが意味ないと思う

2019-11-07 11:58 UTC, amylaseF85 commented on DJYusaku/ListenerConnectionViewController.swift
> +    */
初期状態からあるように見えるんですがコレはこの後必要になる？

2019-11-07 13:27 UTC, tsuu32 commented on DJYusaku/ConnectionController.swift
> +        browser.delegate = self
`func initialize(isParent: Bool, displayName: String)`の中のほうは絶対必要なので、修正するなら
```swift
  var connectableDJs: [MCPeerID] = []
```
のほうでしょう。
意味はないのかもしれませんが、これのせいでバグってるとかはないので、修正しなくてもいい気はします。

2019-11-07 13:29 UTC, tsuu32 commented on DJYusaku/ListenerConnectionViewController.swift
> +    */
これはXcodeでCocoa Touch Classなファイルを作るときに自動で挿入されるコメントアウトです。

今後必要になることはないと思われます。

2019-11-07 13:36 UTC, yaplus requested changes
Delegate呼び出しがメインスレッドになってるところだけ直したらOKです

2019-11-07 13:36 UTC, yaplus commented on DJYusaku/ConnectionControllerDelegate.swift
> +}
didReceiveDataとconnectableDevicesChangedでdid＋現在形と過去形になってるの若干気になる

2019-11-07 13:36 UTC, yaplus commented on DJYusaku/ConnectionController.swift
> +        }
Delegateの処理をメインスレッドで実行するのをやめなさーい😾

2019-11-07 13:59 UTC, amylaseF85 commented on DJYusaku/ListenerConnectionViewController.swift
> +    */
問題なさそうなら消しておいて下さい

2019-11-09 02:05 UTC, tsuu32 commented on DJYusaku/ConnectionController.swift
> +        }
修正しました。

2019-11-09 02:06 UTC, tsuu32 commented on DJYusaku/ConnectionControllerDelegate.swift
> +}
connectableDevicesChangedをdidChangeConnectableDevicesに改名しました

2019-11-09 02:10 UTC, yaplus commented
Notification以外は過去分詞の方に揃えた方がいい気がしたんだけど、どうだろう（didReceiveData:data とかreceivedData: dataの方が良くない？）

2019-11-09 02:15 UTC, tsuu32 commented
https://developer.apple.com/documentation/multipeerconnectivity/mcsessiondelegate
MCSessionDelegateのメソッドらはdid+動詞が使われてるよ

2019-11-09 02:25 UTC, tsuu32 commented
@bldsky 
今気づいたんだけど、MCSession+sendRequest.swiftファイルがDJYusakuディレクトリの中じゃなくてリポジトリのルートにあるのはミス？それとも意図的？

2019-11-09 02:36 UTC, yaplus commented
すいません、Coding Guidelines for Cocoaの[Delgate Method](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-1004202-BCIGGFCC)の項読んでたら

>Use “did” or “will” for methods that are invoked to notify the delegate that something has happened or is about to happen.

> Although you can use “did” or “will” for methods that are invoked to ask the delegate to do something on behalf of another object, “should” is preferred.

ってあるしこれで大丈夫っぽいです。

2019-11-09 02:36 UTC, yaplus commented
MCSession+sendRequest.swiftの位置が直り次第マージします

2019-11-09 02:38 UTC, yaplus commented
@tsuu32 
多分ミスだと思うからそっちで直しておいてくれると助かる

2019-11-09 02:41 UTC, yaplus approved these changes

2019-11-09 02:52 UTC, yaplus approved these changes
みました  
通信するためにバンドル名揃えなきゃいけないのでこれマージして僕のバンドルIDに書き換えたらTestFlight登録します #26

2019-11-09 02:52 UTC, tsuu32 commented
b10f8fc でMCSession+sendRequest.swiftの位置を変更しました
ビルドして試してもエラーは出なかったので大丈夫だと思います

2019-11-09 02:53 UTC, merged