DJからListenerになるときのバグを修正
enpitut2019/dj-yusaku pull request #38
Opened 2019-11-15 06:59 UTC by tsuu32

## 概要
現在DJであるデバイスが [join as a Listener] を押すと、一瞬自分が見えてしまう不具合を直す。

## 詳しい説明
ListenerConnectionViewController では viewDidLoad() で ConnectionController.shared.initialize() している。（このときconnectableDJsは空になる）

その後すぐConnectionController.shared.startBrowse() を始めるが、このとき DJ だったときのadvertiseを検知して表示してしまう。しかし、これはその後すぐ消える。

## 謎
以前までもadvertiseを止めていないのに一瞬たったら消えるのはなぜ？ (ガベージコレクション的なか？)

そもそもなぜ自分が出てきてしまうのか？

2019-11-15 07:05 UTC, tsuu32 commented
a1b9bc1 でいい感じに直せました
（6d9439f のコミットメッセージ間違えた...）

2019-11-15 17:19 UTC, tsuu32 commented
なんでpeerIDをinitializeで作り直す設計にしたのか思い出しました。
現在のinitialize関数ではdisplayNameを引数にとって、それをpeerIDオブジェクト作成に利用します（これがbrowseの画面で出てくる端末を識別するための文字列になる）。
将来実装する（かもしれない）自分の端末に別の名前つけられたらいいよねって機能のためにこうしていたんでした（現在もこのPRもdisplayNameは`UIDevice.current.name`決め打ちなんだけれど...）。

2019-11-17 13:38 UTC, amylaseF85 reviewed
気になる所はないけど、問題ないかがわからん
@bldskyあたり頼む🙏

2019-11-18 04:33 UTC, bldsky commented on DJYusaku/ConnectionController.swift
>          // print(self.delegate)
# デバッグ用のprintは消したほうがいいんじゃない?

2019-11-18 04:33 UTC, bldsky commented on DJYusaku/ConnectionController.swift
> +        print("browser: connectable DJ (\(peerID)) is lost")
# 上と同じ

2019-11-18 04:34 UTC, bldsky requested changes
終わり

2019-11-18 04:34 UTC, bldsky approved these changes

2019-11-18 07:10 UTC, tsuu32 commented
今の状態では`ConnectionController`のdisplayNameプロパティが無意味になってしまっていますが、まあ後で考えましょう。

2019-11-18 07:11 UTC, merged