タブを押した時にアイコンがバウンドするフィードバックを追加　ほか
enpitut2019/dj-yusaku pull request #57
Opened 2019-12-10 05:32 UTC by amylaseF85

## 概要
-タブを押した時、今まで無反応で無機質であったところに、タブを押すとバウンドするアニメーションを追加することでユーザー体験がリッチになった
- 削除機能を殺した

## やったこと
- TabBarController.swiftにタブを押した時のアニメーション処理を追加
- アニメーションを追加するにあたり、各タブのViewにtagをそれぞれ付与
　　- requestを0、sessionを2としている
　　- @yaplusが追加したやつは使わないけど1を付与している
- RequestViewControllerに削除機能を殺しつつ編集機能だけを有効にする記述を追加

## お願い
コードレビュー並びに動作確認をお願いします
今回関数名と変数名にすこぶる自信がないのでいい名前あったらお願いします
あと、アニメーションの部分のプロパティでこうした方がいいと感じたら言ってください
```  swift
        UIView.animateKeyframes(withDuration: 0.4, delay: 0, options: [], animations: {() -> Void in
            UIView.addKeyframe(withRelativeStartTime: 0.0, relativeDuration: 0.3, animations: {() -> Void in
                tabImageView.transform = CGAffineTransform(scaleX: CGFloat(0.8), y: CGFloat(0.8))
            })
            UIView.addKeyframe(withRelativeStartTime: 0.4, relativeDuration: 0.3, animations: {() -> Void in
                tabImageView.transform = CGAffineTransform.identity
            })
```
ここのところ

## その他
グレーアウトの機能は付けなかった（誰が着手するべきだったか忘れた…）
このプルリクで一緒に来ると想定してた場合は言ってください

2019-12-10 08:36 UTC, yaplus commented
グレーアウトの機能もつけちゃっていいよ

2019-12-11 09:51 UTC, amylaseF85 commented
> グレーアウトの機能もつけちゃっていいよ

つけた

2019-12-12 12:55 UTC, yaplus approved these changes
大丈夫そうだけど、とりあえずコメントした箇所は確認して（必要であれば）変更してからマージしてほしい

2019-12-12 12:55 UTC, yaplus commented on DJYusaku/Base.lproj/Main.storyboard
> +                    <tabBarItem key="tabBarItem" tag="1" title="" id="e6F-GQ-N3B"/>
ここの`tag="1"`なのに

2019-12-12 12:55 UTC, yaplus commented on DJYusaku/TabBarController.swift
> +        case 0:
（StoryboardのTabBarItemは`tag="1"`になってるのに）ここが`case 0:`なのが気になる

2019-12-12 12:55 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> -        tableView.delegate = self
TableViewのデリゲート部分は削除・編集関係だけ削除してdelegate設定と空のデリゲートメソッドだけ残しててもいいかなあと思ったけど、また気が変わって削除・編集機能を入れる時に忘れなければ（今は）OKです。

2019-12-12 12:55 UTC, yaplus commented on DJYusaku/TabBarController.swift
> +    @objc func plusButton() {
なんだこの余白

2019-12-12 13:09 UTC, amylaseF85 commented on DJYusaku/Base.lproj/Main.storyboard
> +                    <tabBarItem key="tabBarItem" tag="1" title="" id="e6F-GQ-N3B"/>
tabBarのやつに回答

2019-12-12 13:11 UTC, amylaseF85 commented on DJYusaku/TabBarController.swift
> +        case 0:
id : e6F-GQ-N3Bは、＋ボタンのとこにある空のモーダルの番号
一応Viewがあるということであえて通し番号にしなかったんだけど、気持ち悪かったら変える

2019-12-12 13:11 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> -        tableView.delegate = self
消しちゃう

2019-12-12 13:11 UTC, amylaseF85 commented on DJYusaku/TabBarController.swift
> +    @objc func plusButton() {
なんでやろな

2019-12-12 13:15 UTC, yaplus commented on DJYusaku/TabBarController.swift
> +        case 0:
パッと見わかりづらいからコメント書くなりenum（定数）にするなりした方がいいんじゃないかな

2019-12-12 13:15 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> -        tableView.delegate = self
OK

2019-12-12 13:15 UTC, yaplus commented on DJYusaku/TabBarController.swift
> +    @objc func plusButton() {
オイオイオイ

2019-12-12 13:17 UTC, amylaseF85 commented on DJYusaku/TabBarController.swift
> +        case 0:
enumにして再プッシュします

2019-12-12 13:37 UTC, amylaseF85 commented on DJYusaku/TabBarController.swift
> +        case 0:
やた

2019-12-12 13:53 UTC, bldsky reviewed
いいね

2019-12-12 14:10 UTC, yaplus requested changes

2019-12-12 14:10 UTC, yaplus commented on DJYusaku/RequestsViewController.swift
> -        tableView.dataSource = self
dataSource消してるけど大丈夫か？

2019-12-12 14:11 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> -        tableView.dataSource = self
間違えました

2019-12-12 14:12 UTC, amylaseF85 commented on DJYusaku/RequestsViewController.swift
> -        tableView.dataSource = self
というか、見方間違えてた

2019-12-12 14:13 UTC, yaplus approved these changes
多分大丈夫だと思います　動作確認してバグあったらこっちで直す

2019-12-12 14:13 UTC, merged